export const CHANGE_COLOR_CARD_VALUE = 'Change Color';
export const TWO_PLUS='2+';
export const HUMAN = 'Human';
export const SUPER_TAKI='Super Taki'
export const PLUS_CARD = "+"
export const DECK_OF_CARDS = 'deck';
export const COMPUTER = 'Computer';
export const WHITE_COLOR = 'white';
export const TAKI_CARD_VALUE = 'Taki'
export const STOP_CARD_VALUE = 'Stop'
export const CARDS_VALUE = ['1', '3', '4', '5', '6', '7', '8', '9', STOP_CARD_VALUE, TAKI_CARD_VALUE, PLUS_CARD,TWO_PLUS, CHANGE_COLOR_CARD_VALUE];
export const CARDS_COLOR = ['green', 'yellow', 'red', 'blue'];
export const INIT_NUM_CARDS = 8;
export const VISIBLE = 'visible'
export const HIDDEN = 'hidden';
export const STATS_TOTAL_TURN_VALUE = "STATS_TOTAL_TURN_VALUE";
export const STATS_TIMES_WITH_SINGLE_VALUE = "STATS_TIMES_WITH_SINGLE_VALUE";
export const COMPUTER_DELAY_IN_MS=1000;